<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 

 class Bus
 {
    
    /**
     * @var string
     */
     protected $serviceclass;
    
    /**
     * @var string
     */
     protected $name;
    
    /**
     * @var string
     */
     protected $id;
    
    
    /**
     * Get serviceClass
     *
     * @return string
     */
     public function getServiceclass()
     {
        return $this->serviceClass;
     }
    
    /**
     * Set serviceClass
     *
     * @param string $serviceClass
     */
     public function setServiceclass($serviceClass)
     {
        $this->serviceClass = $serviceClass;
     }
     
    /**
     * Get name
     *
     * @return string
     */
     public function getName()
     {
        return $this->name;
     }
    
    /**
     * Set name
     *
     * @param string $name
     */
     public function setName($name)
     {
        $this->name = $name;
     }
     
    /**
     * Get id
     *
     * @return integer
     */
     public function getId()
     {
        return $this->id;
     }
    
    /**
     * Set id
     *
     * @param integer $id
     */
     public function setId($id)
     {
        $this->id = $id;
     }
     
 }
