<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Total;
use Json2Dto\Servicefee;
use Json2Dto\Servicefeepercentage;


 class Creditcard
 {
    
    /**
     * @var Total
     */
     protected $total;
    
    /**
     * @var string
     */
     protected $fixedvalue;
    
    /**
     * @var Servicefee
     */
     protected $servicefee;
    
    /**
     * @var Servicefeepercentage
     */
     protected $servicefeepercentage;
    
    
    /**
     * Get total
     *
     * @return Total
     */
     public function getTotal()
     {
        return $this->total;
     }
    
    /**
     * Set total
     *
     * @param Total $total
     */
     public function setTotal(Total $total)
     {
        $this->total = $total;
     }
    
    /**
     * Get fixedValue
     *
     * @return integer
     */
     public function getFixedvalue()
     {
        return $this->fixedValue;
     }
    
    /**
     * Set fixedValue
     *
     * @param integer $fixedValue
     */
     public function setFixedvalue($fixedValue)
     {
        $this->fixedValue = $fixedValue;
     }
     
    /**
     * Get serviceFee
     *
     * @return Servicefee
     */
     public function getServicefee()
     {
        return $this->serviceFee;
     }
    
    /**
     * Set serviceFee
     *
     * @param Servicefee $serviceFee
     */
     public function setServicefee(Servicefee $serviceFee)
     {
        $this->serviceFee = $serviceFee;
     }
    
    /**
     * Get serviceFeePercentage
     *
     * @return Servicefeepercentage
     */
     public function getServicefeepercentage()
     {
        return $this->serviceFeePercentage;
     }
    
    /**
     * Set serviceFeePercentage
     *
     * @param Servicefeepercentage $serviceFeePercentage
     */
     public function setServicefeepercentage(Servicefeepercentage $serviceFeePercentage)
     {
        $this->serviceFeePercentage = $serviceFeePercentage;
     }
    
 }
