<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 

 class Debitcard
 {
    
    /**
     * @var string
     */
     protected $total;
    
    /**
     * @var string
     */
     protected $fixedvalue;
    
    /**
     * @var string
     */
     protected $servicefee;
    
    /**
     * @var string
     */
     protected $servicefeepercentage;
    
    
    /**
     * Get total
     *
     * @return string
     */
     public function getTotal()
     {
        return $this->total;
     }
    
    /**
     * Set total
     *
     * @param string $total
     */
     public function setTotal($total)
     {
        $this->total = $total;
     }
     
    /**
     * Get fixedValue
     *
     * @return integer
     */
     public function getFixedvalue()
     {
        return $this->fixedValue;
     }
    
    /**
     * Set fixedValue
     *
     * @param integer $fixedValue
     */
     public function setFixedvalue($fixedValue)
     {
        $this->fixedValue = $fixedValue;
     }
     
    /**
     * Get serviceFee
     *
     * @return integer
     */
     public function getServicefee()
     {
        return $this->serviceFee;
     }
    
    /**
     * Set serviceFee
     *
     * @param integer $serviceFee
     */
     public function setServicefee($serviceFee)
     {
        $this->serviceFee = $serviceFee;
     }
     
    /**
     * Get serviceFeePercentage
     *
     * @return string
     */
     public function getServicefeepercentage()
     {
        return $this->serviceFeePercentage;
     }
    
    /**
     * Set serviceFeePercentage
     *
     * @param string $serviceFeePercentage
     */
     public function setServicefeepercentage($serviceFeePercentage)
     {
        $this->serviceFeePercentage = $serviceFeePercentage;
     }
     
 }
