<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Waypoint;


 class Departure
 {
    
    /**
     * @var string
     */
     protected $price;
    
    /**
     * @var Waypoint
     */
     protected $waypoint;
    
    
    /**
     * Get price
     *
     * @return integer
     */
     public function getPrice()
     {
        return $this->price;
     }
    
    /**
     * Set price
     *
     * @param integer $price
     */
     public function setPrice($price)
     {
        $this->price = $price;
     }
     
    /**
     * Get waypoint
     *
     * @return Waypoint
     */
     public function getWaypoint()
     {
        return $this->waypoint;
     }
    
    /**
     * Set waypoint
     *
     * @param Waypoint $waypoint
     */
     public function setWaypoint(Waypoint $waypoint)
     {
        $this->waypoint = $waypoint;
     }
    
 }
