<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Paymentsettings;
use Json2Dto\Items;


 class Dto
 {
    
    /**
     * @var string
     */
     protected $meta;
    
    /**
     * @var Paymentsettings
     */
     protected $paymentsettings;
    
    /**
     * @var Items
     */
     protected $items = array();
    
    
    /**
     * Get meta
     *
     * @return string
     */
     public function getMeta()
     {
        return $this->meta;
     }
    
    /**
     * Set meta
     *
     * @param string $meta
     */
     public function setMeta($meta)
     {
        $this->meta = $meta;
     }
     
    /**
     * Get paymentSettings
     *
     * @return Paymentsettings
     */
     public function getPaymentsettings()
     {
        return $this->paymentSettings;
     }
    
    /**
     * Set paymentSettings
     *
     * @param Paymentsettings $paymentSettings
     */
     public function setPaymentsettings(Paymentsettings $paymentSettings)
     {
        $this->paymentSettings = $paymentSettings;
     }
    
    /**
     * Get items
     *
     * @return Items
     */
     public function getItems()
     {
        return $this->items;
     }
    
    /**
     * Add items
     *
     * @param $items
     */
     public function addItems(Items $items)
     {
        $this->items[] = $items;
     }
    
 }
