<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Parts;


 class Items
 {
    
    /**
     * @var string
     */
     protected $from;
    
    /**
     * @var string
     */
     protected $to;
    
    /**
     * @var string
     */
     protected $bookingEngine;
    
    /**
     * @var Parts
     */
     protected $parts = array();
    
    
    /**
     * Get from
     *
     * @return string
     */
     public function getFrom()
     {
        return $this->from;
     }
    
    /**
     * Set from
     *
     * @param string $from
     */
     public function setFrom($from)
     {
        $this->from = $from;
     }
     
    /**
     * Get to
     *
     * @return string
     */
     public function getTo()
     {
        return $this->to;
     }
    
    /**
     * Set to
     *
     * @param string $to
     */
     public function setTo($to)
     {
        $this->to = $to;
     }
     
    /**
     * Get booking_engine
     *
     * @return string
     */
     public function getBookingEngine()
     {
        return $this->booking_engine;
     }
    
    /**
     * Set booking_engine
     *
     * @param string $booking_engine
     */
     public function setBookingEngine($booking_engine)
     {
        $this->booking_engine = $booking_engine;
     }
     
    /**
     * Get parts
     *
     * @return Parts
     */
     public function getParts()
     {
        return $this->parts;
     }
    
    /**
     * Add parts
     *
     * @param $parts
     */
     public function addParts(Parts $parts)
     {
        $this->parts[] = $parts;
     }
    
 }
