<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Bankslip;
use Json2Dto\Creditcard;
use Json2Dto\Debitcard;
use Json2Dto\PaypalHpp;
use Json2Dto\Banktransfer;


 class PaymentSettings
 {
    
    /**
     * @var Bankslip
     */
     protected $bankslip;
    
    /**
     * @var Creditcard
     */
     protected $creditcard;
    
    /**
     * @var Debitcard
     */
     protected $debitcard;
    
    /**
     * @var PaypalHpp
     */
     protected $paypalHpp;
    
    /**
     * @var Banktransfer
     */
     protected $banktransfer;
    
    
    /**
     * Get bankslip
     *
     * @return Bankslip
     */
     public function getBankslip()
     {
        return $this->bankslip;
     }
    
    /**
     * Set bankslip
     *
     * @param Bankslip $bankslip
     */
     public function setBankslip(Bankslip $bankslip)
     {
        $this->bankslip = $bankslip;
     }
    
    /**
     * Get creditcard
     *
     * @return Creditcard
     */
     public function getCreditcard()
     {
        return $this->creditcard;
     }
    
    /**
     * Set creditcard
     *
     * @param Creditcard $creditcard
     */
     public function setCreditcard(Creditcard $creditcard)
     {
        $this->creditcard = $creditcard;
     }
    
    /**
     * Get debitcard
     *
     * @return Debitcard
     */
     public function getDebitcard()
     {
        return $this->debitcard;
     }
    
    /**
     * Set debitcard
     *
     * @param Debitcard $debitcard
     */
     public function setDebitcard(Debitcard $debitcard)
     {
        $this->debitcard = $debitcard;
     }
    
    /**
     * Get paypal_hpp
     *
     * @return PaypalHpp
     */
     public function getPaypalHpp()
     {
        return $this->paypal_hpp;
     }
    
    /**
     * Set paypal_hpp
     *
     * @param PaypalHpp $paypal_hpp
     */
     public function setPaypalHpp(PaypalHpp $paypal_hpp)
     {
        $this->paypal_hpp = $paypal_hpp;
     }
    
    /**
     * Get banktransfer
     *
     * @return Banktransfer
     */
     public function getBanktransfer()
     {
        return $this->banktransfer;
     }
    
    /**
     * Set banktransfer
     *
     * @param Banktransfer $banktransfer
     */
     public function setBanktransfer(Banktransfer $banktransfer)
     {
        $this->banktransfer = $banktransfer;
     }
    
 }
