<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Station;


 class Place
 {
    
    /**
     * @var string
     */
     protected $country;
    
    /**
     * @var string
     */
     protected $state;
    
    /**
     * @var string
     */
     protected $city;
    
    /**
     * @var Station
     */
     protected $station;
    
    /**
     * @var string
     */
     protected $locale;
    
    /**
     * @var string
     */
     protected $id;
    
    
    /**
     * Get country
     *
     * @return string
     */
     public function getCountry()
     {
        return $this->country;
     }
    
    /**
     * Set country
     *
     * @param string $country
     */
     public function setCountry($country)
     {
        $this->country = $country;
     }
     
    /**
     * Get state
     *
     * @return string
     */
     public function getState()
     {
        return $this->state;
     }
    
    /**
     * Set state
     *
     * @param string $state
     */
     public function setState($state)
     {
        $this->state = $state;
     }
     
    /**
     * Get city
     *
     * @return string
     */
     public function getCity()
     {
        return $this->city;
     }
    
    /**
     * Set city
     *
     * @param string $city
     */
     public function setCity($city)
     {
        $this->city = $city;
     }
     
    /**
     * Get station
     *
     * @return Station
     */
     public function getStation()
     {
        return $this->station;
     }
    
    /**
     * Set station
     *
     * @param Station $station
     */
     public function setStation(Station $station)
     {
        $this->station = $station;
     }
    
    /**
     * Get locale
     *
     * @return string
     */
     public function getLocale()
     {
        return $this->locale;
     }
    
    /**
     * Set locale
     *
     * @param string $locale
     */
     public function setLocale($locale)
     {
        $this->locale = $locale;
     }
     
    /**
     * Get id
     *
     * @return integer
     */
     public function getId()
     {
        return $this->id;
     }
    
    /**
     * Set id
     *
     * @param integer $id
     */
     public function setId($id)
     {
        $this->id = $id;
     }
     
 }
