<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 

 class Products
 {
    
    /**
     * @var string
     */
     protected $uuid;
    
    /**
     * @var string
     */
     protected $name;
    
    /**
     * @var string
     */
     protected $price;
    
    /**
     * @var string
     */
     protected $currency;
    
    /**
     * @var string
     */
     protected $avaliable;
    
    
    /**
     * Get uuid
     *
     * @return string
     */
     public function getUuid()
     {
        return $this->uuid;
     }
    
    /**
     * Set uuid
     *
     * @param string $uuid
     */
     public function setUuid($uuid)
     {
        $this->uuid = $uuid;
     }
     
    /**
     * Get name
     *
     * @return string
     */
     public function getName()
     {
        return $this->name;
     }
    
    /**
     * Set name
     *
     * @param string $name
     */
     public function setName($name)
     {
        $this->name = $name;
     }
     
    /**
     * Get price
     *
     * @return integer
     */
     public function getPrice()
     {
        return $this->price;
     }
    
    /**
     * Set price
     *
     * @param integer $price
     */
     public function setPrice($price)
     {
        $this->price = $price;
     }
     
    /**
     * Get currency
     *
     * @return string
     */
     public function getCurrency()
     {
        return $this->currency;
     }
    
    /**
     * Set currency
     *
     * @param string $currency
     */
     public function setCurrency($currency)
     {
        $this->currency = $currency;
     }
     
    /**
     * Get avaliable
     *
     * @return boolean
     */
     public function getAvaliable()
     {
        return $this->avaliable;
     }
    
    /**
     * Set avaliable
     *
     * @param boolean $avaliable
     */
     public function setAvaliable($avaliable)
     {
        $this->avaliable = $avaliable;
     }
     
 }
