<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 

 class ServiceFeePercentage
 {
    
    /**
     * @var integer
     */
     protected $1;
    
    /**
     * @var integer
     */
     protected $2;
    
    /**
     * @var integer
     */
     protected $3;
    
    /**
     * @var integer
     */
     protected $4;
    
    /**
     * @var integer
     */
     protected $5;
    
    /**
     * @var integer
     */
     protected $6;
    
    /**
     * @var integer
     */
     protected $7;
    
    /**
     * @var integer
     */
     protected $8;
    
    /**
     * @var integer
     */
     protected $9;
    
    /**
     * @var integer
     */
     protected $10;
    
    /**
     * @var integer
     */
     protected $11;
    
    /**
     * @var integer
     */
     protected $12;
    
    
    /**
     * Get 1
     *
     * @return string
     */
     public function get1()
     {
        return $this->1;
     }
    
    /**
     * Set 1
     *
     * @param string $1
     */
     public function set1($1)
     {
        $this->1 = $1;
     }
     
    /**
     * Get 2
     *
     * @return string
     */
     public function get2()
     {
        return $this->2;
     }
    
    /**
     * Set 2
     *
     * @param string $2
     */
     public function set2($2)
     {
        $this->2 = $2;
     }
     
    /**
     * Get 3
     *
     * @return string
     */
     public function get3()
     {
        return $this->3;
     }
    
    /**
     * Set 3
     *
     * @param string $3
     */
     public function set3($3)
     {
        $this->3 = $3;
     }
     
    /**
     * Get 4
     *
     * @return string
     */
     public function get4()
     {
        return $this->4;
     }
    
    /**
     * Set 4
     *
     * @param string $4
     */
     public function set4($4)
     {
        $this->4 = $4;
     }
     
    /**
     * Get 5
     *
     * @return string
     */
     public function get5()
     {
        return $this->5;
     }
    
    /**
     * Set 5
     *
     * @param string $5
     */
     public function set5($5)
     {
        $this->5 = $5;
     }
     
    /**
     * Get 6
     *
     * @return string
     */
     public function get6()
     {
        return $this->6;
     }
    
    /**
     * Set 6
     *
     * @param string $6
     */
     public function set6($6)
     {
        $this->6 = $6;
     }
     
    /**
     * Get 7
     *
     * @return string
     */
     public function get7()
     {
        return $this->7;
     }
    
    /**
     * Set 7
     *
     * @param string $7
     */
     public function set7($7)
     {
        $this->7 = $7;
     }
     
    /**
     * Get 8
     *
     * @return string
     */
     public function get8()
     {
        return $this->8;
     }
    
    /**
     * Set 8
     *
     * @param string $8
     */
     public function set8($8)
     {
        $this->8 = $8;
     }
     
    /**
     * Get 9
     *
     * @return string
     */
     public function get9()
     {
        return $this->9;
     }
    
    /**
     * Set 9
     *
     * @param string $9
     */
     public function set9($9)
     {
        $this->9 = $9;
     }
     
    /**
     * Get 10
     *
     * @return string
     */
     public function get10()
     {
        return $this->10;
     }
    
    /**
     * Set 10
     *
     * @param string $10
     */
     public function set10($10)
     {
        $this->10 = $10;
     }
     
    /**
     * Get 11
     *
     * @return string
     */
     public function get11()
     {
        return $this->11;
     }
    
    /**
     * Set 11
     *
     * @param string $11
     */
     public function set11($11)
     {
        $this->11 = $11;
     }
     
    /**
     * Get 12
     *
     * @return string
     */
     public function get12()
     {
        return $this->12;
     }
    
    /**
     * Set 12
     *
     * @param string $12
     */
     public function set12($12)
     {
        $this->12 = $12;
     }
     
 }
