<?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;

 use Json2Dto\Prices;
use Json2Dto\Schedule;
use Json2Dto\Place;


 class Waypoints
 {
    
    /**
     * @var string
     */
     protected $id;
    
    /**
     * @var Prices
     */
     protected $prices = array();
    
    /**
     * @var Schedule
     */
     protected $schedule;
    
    /**
     * @var string
     */
     protected $context;
    
    /**
     * @var Place
     */
     protected $place;
    
    /**
     * @var string
     */
     protected $isdeparture;
    
    /**
     * @var string
     */
     protected $position;
    
    
    /**
     * Get id
     *
     * @return integer
     */
     public function getId()
     {
        return $this->id;
     }
    
    /**
     * Set id
     *
     * @param integer $id
     */
     public function setId($id)
     {
        $this->id = $id;
     }
     
    /**
     * Get prices
     *
     * @return Prices
     */
     public function getPrices()
     {
        return $this->prices;
     }
    
    /**
     * Add prices
     *
     * @param $prices
     */
     public function addPrices(Prices $prices)
     {
        $this->prices[] = $prices;
     }
    
    /**
     * Get schedule
     *
     * @return Schedule
     */
     public function getSchedule()
     {
        return $this->schedule;
     }
    
    /**
     * Set schedule
     *
     * @param Schedule $schedule
     */
     public function setSchedule(Schedule $schedule)
     {
        $this->schedule = $schedule;
     }
    
    /**
     * Get context
     *
     * @return string
     */
     public function getContext()
     {
        return $this->context;
     }
    
    /**
     * Set context
     *
     * @param string $context
     */
     public function setContext($context)
     {
        $this->context = $context;
     }
     
    /**
     * Get place
     *
     * @return Place
     */
     public function getPlace()
     {
        return $this->place;
     }
    
    /**
     * Set place
     *
     * @param Place $place
     */
     public function setPlace(Place $place)
     {
        $this->place = $place;
     }
    
    /**
     * Get isDeparture
     *
     * @return boolean
     */
     public function getIsdeparture()
     {
        return $this->isDeparture;
     }
    
    /**
     * Set isDeparture
     *
     * @param boolean $isDeparture
     */
     public function setIsdeparture($isDeparture)
     {
        $this->isDeparture = $isDeparture;
     }
     
    /**
     * Get position
     *
     * @return integer
     */
     public function getPosition()
     {
        return $this->position;
     }
    
    /**
     * Set position
     *
     * @param integer $position
     */
     public function setPosition($position)
     {
        $this->position = $position;
     }
     
 }
