#!/usr/bin/env php
<?php
$autoloaders = array(
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
);

foreach ($autoloaders as $file) {
    if (file_exists($file)) {
        define('JSON2DTO_COMPOSER_INSTALL', $file);
        break;
    }
}

require JSON2DTO_COMPOSER_INSTALL;

\Json2Dto\Command::main();
