<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 6/21/14
 * Time: 1:12 AM
 */

namespace Json2DtoTests;


use Json2Dto\Writer;

class WriterTest extends \PHPUnit_Framework_TestCase
{
    protected $writer;

    protected $objects = array(
        "Dto" => array(
            "arguments"  => '/**
     * @var meta
     */
     protected $meta;

    /**
     * @var Paymentsettings
     */
     protected $paymentsettings;

    /**
     * @var Items
     */
     protected $items = array();',
        "methods" =>
            '/**
     * Get meta
     *
     * @return $meta
     */
     public function getMeta()
     {
        return $this->meta;
     }

    /**
     * Set meta
     *
     * @param string $meta
     */
     public function setMeta($meta)
     {
        $this->meta = $meta;
     }

    /**
     * Get paymentSettings
     *
     * @return $paymentSettings
     */
     public function getPaymentsettings()
     {
        return $this->paymentSettings;
     }

    /**
     * Set paymentSettings
     *
     * @param Paymentsettings $paymentSettings
     */
     public function setPaymentsettings(Paymentsettings $paymentSettings)
     {
        $this->paymentSettings = $paymentSettings;
     }

    /**
     * Get items
     *
     * @return $items
     */
     public function getItems()
     {
        return $this->items;
     }

    /**
     * Add items
     *
     * @param $items
     */
     public function addItems(Items $items)
     {
        $this->items[] = $items;
     }',
    "use" => 'use Json2Dto\Paymentsettings;
use Json2Dto\Items;',
    "class" => '&lt;?php
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 namespace Json2Dto;


use Json2Dto\Paymentsettings;
use Json2Dto\Items;

 class Dto
 {

    /**
     * @var meta
     */
     protected $meta;

    /**
     * @var Paymentsettings
     */
     protected $paymentsettings;

    /**
     * @var Items
     */
     protected $items = array();



    /**
     * Get meta
     *
     * @return $meta
     */
     public function getMeta()
     {
        return $this->meta;
     }

    /**
     * Set meta
     *
     * @param string $meta
     */
     public function setMeta($meta)
     {
        $this->meta = $meta;
     }

    /**
     * Get paymentSettings
     *
     * @return $paymentSettings
     */
     public function getPaymentsettings()
     {
        return $this->paymentSettings;
     }

    /**
     * Set paymentSettings
     *
     * @param Paymentsettings $paymentSettings
     */
     public function setPaymentsettings(Paymentsettings $paymentSettings)
     {
        $this->paymentSettings = $paymentSettings;
     }

    /**
     * Get items
     *
     * @return $items
     */
     public function getItems()
     {
        return $this->items;
     }

    /**
     * Add items
     *
     * @param $items
     */
     public function addItems(Items $items)
     {
        $this->items[] = $items;
     }

 }'
        )
    );

    public function setUp()
    {
        parent::setUp();
        $this->writer = new Writer(__DIR__ . '/Resources/GeneratedFiles/', $this->objects);
    }

    public function testWrite()
    {
        $fileName = __DIR__ . '/Resources/GeneratedFiles/Dto.php';

        $this->assertFalse(file_exists($fileName));
        $this->writer->write();
        $this->assertTrue(file_exists($fileName));
        $this->assertGreaterThan(0, filesize($fileName));
        unlink($fileName);
    }

    /**
     * @expectedException \Json2Dto\Exceptions\ObjectsNotProcessedException
     */
    public function testObjectsNotLoadedException()
    {
        $writer = new Writer('.', array());
    }

    /**
     * @expectedException \Json2Dto\Exceptions\DirectoryNotExistsException
     */
    public function testDirectoryNotExists()
    {
        $writer = new Writer('/a/b/c', array());
    }
}
 