<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 6/20/14
 * Time: 8:17 AM
 */

namespace Json2Dto\Template;


abstract class Classes implements TemplateInterface
{
    public static $template = '
/**
 * ================================================
 * DTO Generated by Json2Dto
 *
 * @author Tiago Butzke <tiago.butzke@gmail.com>
 * ================================================
 */
 %1$s

 class %2$s
 {
    %3$s

    %4$s
 }
';

    public static function getTemplate()
    {
        return self::$template;
    }
} 